In [1]:
import pandas as pd

In [2]:
header = [
    "regine",
    "TOTN_agri",
    "TOTN_back",
    "DIN_agri",
    "DIN_back",
    "TOTP_agri",
    "TOTP_back",
    "TDP_agri",
    "TDP_back",
    "SS_agri",
    "SS_back",
    "TOC_agri",
    "TOC_back",
]
pars = ["TOTN", "DIN", "TOTP", "TDP", "SS", "TOC"]
df_list = []
scenarios = ["Baseline", "SCA", "SCB"]
for year in range(2017, 2020):
    for scen in scenarios:
        xl_path = f"/home/jovyan/shared/common/oslofjord_modelling/phase3_scenarios/agri_raw/agri_data_v20250912/Leveranse_{year}.xlsx"
        df = pd.read_excel(
            xl_path, sheet_name=scen, header=None, names=header, skiprows=2
        )
        df["scenario"] = scen
        df["year"] = year
        df_list.append(df)
df = pd.concat(df_list, axis="rows")
for par in pars:
    df[par] = df[f"{par}_agri"] #+ df[f"{par}_back"]
    del df[f"{par}_agri"], df[f"{par}_back"]
df.head()

,regine,scenario,year,TOTN,DIN,TOTP,TDP,SS,TOC
0,001.1A2A,Baseline,2017,7812.403108,6235.650452,258.374752,59.852729,111.622281,0.000000
1,001.1A2B,Baseline,2017,6049.991564,4830.192147,141.120200,42.980150,50.183176,0.000000
2,001.1A3,Baseline,2017,7960.113609,6359.783469,129.888995,39.432323,42.483733,0.000000
3,001.1A40,Baseline,2017,8761.796759,7007.857684,169.193536,48.578193,67.584005,0.000000
4,001.1A4A,Baseline,2017,2762.760137,2205.997664,97.481232,23.638142,45.759806,2.018703

In [3]:
df = df.groupby("scenario").sum(numeric_only=True)
df

,year,TOTN,DIN,TOTP,TDP,SS,TOC
scenario,,,,,,,
Baseline,18089352,5.433436e+07,4.303191e+07,2.570578e+06,483701.284101,1.375646e+06,32527.692900
SCA,18089352,5.342759e+07,4.230649e+07,1.542591e+06,414807.188460,4.944487e+05,20486.384898
SCB,18089352,4.066538e+07,3.209672e+07,8.638556e+05,163530.185086,2.777552e+05,16710.317158

In [4]:
df / 3

,year,TOTN,DIN,TOTP,TDP,SS,TOC
scenario,,,,,,,
Baseline,6029784.0,1.811145e+07,1.434397e+07,856859.405213,161233.761367,458548.515562,10842.564300
SCA,6029784.0,1.780920e+07,1.410216e+07,514197.165358,138269.062820,164816.233501,6828.794966
SCB,6029784.0,1.355513e+07,1.069891e+07,287951.853975,54510.061695,92585.080977,5570.105719

In [5]:
for par in pars:
    base = df.loc["Baseline", par]
    sca = df.loc["SCA", par]
    scb = df.loc["SCB", par]

    sca_pct = 100 * (sca - base) / base
    scb_pct = 100 * (scb - base) / base

    print("")
    print(f"# {par} #######################")
    print(f"SCA: {(sca - base)/1000:.3f} tonnes")
    print(f"SCA: {sca_pct:.1f} %")
    print(f"SCB: {(scb - base)/1000:.3f} tonnes")
    print(f"SCB: {scb_pct:.1f} %")

# TOTN #######################
SCA: -906.770 tonnes
SCA: -1.7 %
SCB: -13668.983 tonnes
SCB: -25.2 %

# DIN #######################
SCA: -725.416 tonnes
SCA: -1.7 %
SCB: -10935.186 tonnes
SCB: -25.4 %

# TOTP #######################
SCA: -1027.987 tonnes
SCA: -40.0 %
SCB: -1706.723 tonnes
SCB: -66.4 %

# TDP #######################
SCA: -68.894 tonnes
SCA: -14.2 %
SCB: -320.171 tonnes
SCB: -66.2 %

# SS #######################
SCA: -881.197 tonnes
SCA: -64.1 %
SCB: -1097.890 tonnes
SCB: -79.8 %

# TOC #######################
SCA: -12.041 tonnes
SCA: -37.0 %
SCB: -15.817 tonnes
SCB: -48.6 %